[tool.cibuildwheel.linux]
before-all = [
    "yum install -y wget libtool git-all",
    "chmod +x ./scripts/init_linux.sh",
    "./scripts/init_linux.sh",
]

[tool.cibuildwheel.macos]
repair-wheel-command = [
    "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-listdeps {wheel}",
    "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel -v --require-archs {delocate_archs} -w {dest_dir} {wheel}"
]
